### ISSUE TITLE
How to flash to ESP32?

### ISSUE THREAD

**Issue by mazcoder** [runningtoy/InkBird_BLE2MQTT#1]
I'm sure this is a novice question but I am fairly new to ESP32 and unless I can use Arduino IDE I get lost pretty quick. So would you mind including some instructions on how to flash this to a ESP32.

FYI your code looks exactly like what I want to extend the usability of these reasonably priced thermometers. Looks very promising and I appreciate all your hard work!

**Comment by runningtoy** [comment]
- Install PlatformIO and VScode  ([https://platformio.org/install/ide?install=vscode](https://platformio.org/install/ide?install=vscode))

- Clone the project

- load the project
- press upload
