### ISSUE TITLE
If no probe is inserted in the inkbird, it will publish 6552 to MQTT 

### ISSUE THREAD

**Issue by Dbroek** [runningtoy/InkBird_BLE2MQTT#4]
The install went perfect, both wifi and MQTT setup went without a problem. 

The problem is in publishing the values being published to MQTT when no probe is inserted in the Inkbird IBT-6X. 

With reading the serial information from the ESP the following values are posted;

I (1322058) BBQ: Probe 6 has value 6552.000000
I (1322066) BBQ: Publish 6552 to topic inkbird/probe6
I (1323191) BBQ: Probe 1 has value 6552.000000
I (1323198) BBQ: Publish 6552 to topic inkbird/probe1
I (1323198) BBQ: Probe 2 has value 27.000000
I (1323202) BBQ: Publish 27 to topic inkbird/probe2
I (1323202) BBQ: Probe 3 has value 6552.000000
I (1323209) BBQ: Publish 6552 to topic inkbird/probe3
I (1323210) BBQ: Probe 4 has value 6552.000000
I (1323215) BBQ: Publish 6552 to topic inkbird/probe4
I (1323219) BBQ: Probe 5 has value 6552.000000
I (1323224) BBQ: Publish 6552 to topic inkbird/probe5
I (1323228) BBQ: Probe 6 has value 6552.000000
I (1323233) BBQ: Publish 6552 to topic inkbird/probe6

Only probe 2 is connected in the inkbird and the value is correct. The other probes are not being used but give the value of 6552.
When i insert for example probe 1 it will start giving the correct values. 

solution would be if no probe is inserted (maby if the temperature value is above 500) no value should be send to mqtt

**Comment by runningtoy** [comment]
I add an error value check (PROBEERRORVALUE)
see commit [7f0fbc5ea4246f57d853e5fa56adc94706cdf640](https://github.com/runningtoy/InkBird_BLE2MQTT/commit/7f0fbc5ea4246f57d853e5fa56adc94706cdf640)
