### ISSUE TITLE
MQTT won't connect

### ISSUE THREAD

**Issue by satrik** [runningtoy/InkBird_BLE2MQTT#5]
Hi, 
I've the problem that the esp32 connects to the wifi and also shows the probe*/battery values in the console but I don't get it connected to my raspberry pi MQTT server. I've also tried to setup a Mosquitto on my debian laptop, but there i get the same error message below.  
`
[E][WiFiClient.cpp:232] connect(): connect on fd 55, errno: 118, "Host is unreachable"
E (22502) BBQ: MQTT not Connected
`
I can see and ping the esp32 in my network and I can also sub/pub over the raspberry mqtt without any user/password. 

Do you have an idea what could be wrong oder what I could check now?

btw. HARDWARE: ESP32 240MHz, 320KB RAM, 8MB Flash

Thanks
satrik

**Comment by runningtoy** [comment]
Did you set the ip, username, password, port correct?
Does your mqtt server works correctly?

**Comment by satrik** [comment]
Thanks for your comment, but I've already found the issue. 
I use 3 wifi mesh access points at home and it looks like the "WiFi.h" does have trouble to stay connected to only 1 of the 3. As a workaround I use the "WiFiMulti.h" currently and it works.

So no issues with your code :)
