### ISSUE TITLE
What do i set MQTTSERVER and port to?

### ISSUE THREAD

**Issue by fun4stuff** [runningtoy/InkBird_BLE2MQTT#8]
MQTTSERVER "192.168.1.100"
#define MQTTPORT 1883

Can i leave them as the default?
Are these what i use to connect to the esp32 device?

**Comment by barrymossel** [comment]
You apparently don't know what MQTT is. Google that first...

**Comment by DenDeze** [comment]
Use an mqtt server in your local lan... don't use public servers.
